name: wikidart
description: A Dart library for fetching data through Wikimedia API endpoints.
version: 0.0.2
homepage: https://github.com/flikkr/wikidart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.14.4
